### PR TITLE
fix(filter): fix regex in series by tag parser

### LINKED ISSUE #823: Dont work regex groups in target
# BUG REPORT

## What did you expect to see?
If i wrote in some tag (for tagged metric) like "!=~^.*(a|b|c).*$" 
No metric's is written in metric-three and trigger always has been in no_data state

## What did you see instead?

We want use regex group in tagged metric

### PR DESCRIPTION
**Pull request by balalay12**
# PR Summary
This PR fix `series by tags` parser. 
1. Fix regular expression for correct work with regular expressions in tags. Example: `seriesByTag("respCode=~^(4|5)\d{2}")`
2. Now transform function applied to every tag spec. Not for whole value in `seriesByTag()`.
3. If spec was tranformed change `operator` from `equal` to `match`.

Closes #823

### CODE REVIEW

**Comment by kissken** [comment]
before merge we will test it on feature branch :)

File: filter/series_by_tag.go [hunk 1]
```diff
@@ -34,13 +37,15 @@ type TagSpec struct {
 	Value    string
 }
 
-func transformWildcardToRegexpInSeriesByTag(input string) string {
-	var result = input
-	var re = regexp.MustCompile(`\{(.*?)\}`)
-	var correctLengthOfMatchedWildcardIndexesSlice = 4
+func transformWildcardToRegexpInSeriesByTag(input string) (string, bool) {
+	var (
+		result                                     = input
```
Comment (Tetrergeru) [inline filter/series_by_tag.go:42]: I think it would be more ideomatic to use `:=` instead of the var bloc, if it is possible
```suggestion
		result := input
```

File: filter/series_by_tag.go [hunk 2]
```diff
@@ -34,13 +37,15 @@ type TagSpec struct {
...
+		correctLengthOfMatchedWildcardIndexesSlice = 4
```
Comment (Tetrergeru) [inline filter/series_by_tag.go:43]: Maybe we sould make it a constant and also use in `ParseSeriesByTag`, where magic number 4 is used

**Review by Tetrergeru — CHANGES_REQUESTED** [review]
Left some minor suggestions

**Review by Tetrergeru — DISMISSED** [review]

**Comment by kissken** [comment]
потестили, результаты:

seriesByTag("name=~^a.(b|c).d") ✅
seriesByTag('name=~^a.(b|c).d') ❌
seriesByTag('name=a.b.c')❌

**Comment by kissken** [comment]
последние правки были ок

**Comment by kissken** [comment]
влила мастер в ветку

**Review by kissken — APPROVED** [review]

**Review by Tetrergeru — APPROVED** [review]
